---
- name: Comment out default listen port
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "^Listen 80$"
    line: "#Listen 80"

- name: Ensure vhost directory is present
  file:
    path: "/var/www/{{ httpd_domain }}"
    state: directory
    mode: 0755

- name: Deliver html content
  copy:
    src: index.html
    dest: "/var/www/{{ httpd_domain }}/index.html"
    mode: 0644

- name: Setup vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart httpd

- name: Ensure httpd service is enabled and started
  systemd:
    name: httpd
    state: started
    enabled: true
