---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -d "{extends: default, ignore: .*}" .
  ansible-lint
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    published_ports:
#      - 0.0.0.0:8008:80/tcp
provisioner:
  name: ansible
  options:
    vvv: true
verifier:
  name: ansible
