---
- name: Verify
  hosts: all
  tasks:
  - name: Access to web.html
    uri:
      url: "http://localhost:{{ httpd_port }}/"
      method: GET
      status_code: 200
      return_content: true
    register: result_req

  - name: Test content
    assert:
      that:
        - result_req.content == "simple vhost index"
      fail_msg: "{{ result_req.content }}"
